name: Run doc tests
on:
  # schedule:
  #   - cron: '0 0 * * *'
  # pull_request:
  #   types: [opened, reopened, synchronize]
  workflow_dispatch:
  # repository_dispatch:
  #   types: [trigger-tests]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      console: ${{ steps.filter.outputs.console }}
      quickstart: ${{ steps.filter.outputs.quickstart }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: ls -al
      - name: Run all tests
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event_name == 'schedule' }}
        uses: doc-detective/github-action@v1
        with:
          version: dev
          input: ../../modules/get-started/pages/quick-start.adoc
          working_directory: tests/setup-tests
          exit_on_fail: true
          # create a PR/issue only if the workflow wasn't already triggered by a PR
          # create_pr_on_change: true
          # create_issue_on_fail: true
          # token: ${{ env.ACTIONS_BOT_TOKEN }}

      - name: Upload debug artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: doc-detective-output
          path: /home/runner/work/_temp/doc-detective-output.json
        env:
          REDPANDA_GITHUB_TOKEN: ${{ env.ACTIONS_BOT_TOKEN }}
